### ISSUE TITLE
improvement: default overrides part of the chain defination itself

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship#103]
## Overview
For anyone using a custom image for running the chain, need the ability to define `defaultChain`  values in the chain block itself.

## Proposal
Add support for `type: custom` in chain, where one can define all the remaining default values directly into the chain block
```yaml
chains:
- name: test-chain-1
  type: custom
  image: <image for the chain>
  home: <path to home dir>
  binary: <name of binary>
  ...
```

Without changing the default values, one can directly inject a custom chain into the config file and have helm take care of the rest.
