### ISSUE TITLE
improvements: custom scripts

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship#106]
## Overview
Currently all scripts being run inside the chain and relayers are default and available in the `scripts/` dir in the chart.

## Proposal
Make this customizable by pushing the scripts to the `values.yaml`

```yaml
chains:
  - name: gaia-1
    type: cosmos
    numValidators: 2
    build:
      enabled: true
      source: v1.0.1
      script: scripts/build_chain.sh
    scripts:
      genesis: scripts/setup_genesis.sh
      config: scripts/setup_config.sh
      validator: scripts/create_validator
```

The bash scripts should be built ontop of the current scripts, since that has the correct path information as well as the environment variables exposed to them.
