### ISSUE TITLE
feature: add support for `cometMock` directive for chains

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship#131]
## Overview
Since we are running full chains, sometimes it is hard to get some unhappy path tests, forcing the CometBTF layer to behave a certain way. It would be a good feature to run [cometMock](https://github.com/informalsystems/CometMock) which mocks the `CometBTF`.

## Proposal
Users should be able to easily specify a directive for the chain to use `CometMock` by enabling it. Config should look something like:
```yaml
chains:
- name: chain-1
  type: cosmos
  numValidators: 4
  cometMock:
    enabled: true
    image: <custom image of cometMock>
```

## Design
1. Run an additional deployment/statefulset with the chain
2. Run all the validators with an external tendermint flag
3. Spin up CometMock with address of all the validators (might have to wait for all validators to spin up first)

CC: @p-offtermatt
