### ISSUE TITLE
improvements: simplify `resources` in config.yaml file

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship#133]
## Overview
Currently when defining resources for any of the directives in the config file, one has to specify 
```yaml
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 1
    memory: 2Gi
```

## Proposal
For most users don't need to specify `limits` and `requests` for resources since for testing purpose they can be actually the same. In the config file a user should only specify `cpu` and `memory` directly, and we have a helper function to convert it to actual k8s resource
```yaml
resources:
  cpu: 1
  memory: 2Gi
```
