### ISSUE TITLE
improvements: Relayers to specify paths to open between chains

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship#139]
## Overview
Currently on the relayer start, we create the `transfer` port between the chains specified. We should have the ability to create more custom connections between the chains.

## Proposal
Have a `paths` directive in the `relayer` directive to make the connections explicit.
```yaml
relayers:
  - name: hermes-osmo-juno
    type: hermes
    replicas: 1
    chains:
      - osmosis-1
      - juno-1
    paths:
      - name: transfer-port 
        connection: connection-0
        channel: channel-0
        port: transfer
      - name: channel-connection
        connection: connection-0
        channel: channel-1
```

## Questions
* How will the registry service handle multiple connections? Current `/ibc` endpoints follow the IBC schema for chain-registry and only have the type of transfer ibc ports.

**Comment by Anmol1696** [comment]
Change `paths` to `channels` directive. Which is basically a list of objects like:
```yaml
relayers:
  - name: hermes-osmo-juno
    type: hermes
    replicas: 1
    chains:
      - osmosis-1
      - juno-1
    channels:
      - a_chain: osmosis-1
        b_chain: juno-1
        new_connection: true
        a_port: transfer
        b_port: transfer
     - a_chain: osmosis-1
        a_connection: connection-0
        a_port: transfer
        b_port: transfer
```
