### ISSUE TITLE
improvement: configureable number of distributors for `faucet`

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship#156]
## Overview

Currently the spin up time is slow due to number of distributor keys added in the faucet.

## Proposal
Make configureable and expose to the config, variables to the faucet
```yaml
chains:
  - name: osmosis-1
    type: osmosis
    numValidators: 2
    faucet:
      image: <image of faucet>
      distributors: 2   # default 10
    ...
```

Note: We could expose more here too
