### ISSUE TITLE
feature: integrate monitoring and logging

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship#158]
## Overview
For chains running tendermint, we should integrate moniroting and logging for all nodes. Since we mostly run valiidator nodes and cosmos chains, we can directly deploy monitoring tools used by node-operators into the system

## Proposal
Toggle for enableing monitoring and logging:
```yaml
...
monitoring:
  enabled: true
  ports:
    rest: 8010

logging:
  enabled: true
...
```

For logging we could use existing k8s based tools as well, structure the logs so that they are used/indexed properly.

## Reference
* https://artifact-staking.medium.com/setting-up-validator-monitoring-for-cosmos-sdk-blockchains-8ee1676eb4b0
