### ISSUE TITLE
feature: custom faucet addition

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship#225]
## Overview
Alot of the chains are not able to support `cosmjs` facuet, which causes the issues around scaling.

## Proposal
Create a custom go facuet binary that runs inside the docker image of the chain. This faucet will be a wrapper around running `exec` commands for `tx send` tokens.

We will also have the type of faucet be:
```yaml
chains:
- name: osmosis-1
  type: osmosis
  numValidators: 1
  faucet:
    type: starship-faucet
    resources:
      ...
```

`starship-faucet` will have the same endpoints as cosmjs faucet, which are:
* /status
* /credit

## Implementation
* Go microservice with `/credit` endpoint
* Need a queue, with the requests or a lock on performing the send transfer
* Alternatively: Use concurrent addresses, more similar to cosmjs-faucet

## Test
* Add tests for current and new faucets
* Test against non cosmjs compatible chains: injective, evmos
