### ISSUE TITLE
feature: add default setup scripts to be chain specific

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship#273]
## Overview
By default we should be able to support custom chain scripts.

## Proposal
All the components to make this happen already exist.
In `default.yaml`
```yaml
chain:
- neutron:
  ...
  scripts:
    <define chain specific scripts>
```

Note: this will start increasing the size of of the helm charts produced, but is a nice feature to have for custom support.

## Implementation
Support for:
* Neutron
* Injective
And an easy way to expand this feature.
