### ISSUE TITLE
feature: non `localhost` deployment for `explorer`

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship#302]
## Overview
With ingress, we need another flag on explorer and relivent information about settting up routes with non localhost setup

## Proposal
Add `hosts` along with localhost.
```yaml
explorer:
  enabled: true
  type: ping-pub
  localhost: true
```

For ingressed resources:
```yaml
explorer:
  enabled: true
  type: ping-pub
  hosts:
    - chain: osmosis-1
      endpoints:
        - "https://rpc.osmosis-1.example.com"  
```

Adding hosts will also alow us to run explorer for testnets and mainnets, since we just take the input required per explorer type.

## Alternatives
1. Remove`localhost` and add all as hosts.
2. Only take hostname as input, and generate all the domains for the chains implicitly. Will make the system alot brittle.
