### ISSUE TITLE
Bug : Port forwarding doesn't work 

### ISSUE THREAD

**Issue by Kayanski** [cosmology-tech/starship#457]
I'm using Starship with helm version 0.2.2
I'm using the following command to start the cluster : 
```sh
starship start
```

When starting the cluster, the port-forwarding doesn't work. It seems to use the `name` field to port-forward on kubectl while the helm cluster seems to use the `id` field instead (because those 2 are inter-changed now I guess ?)

Could you fix that in the next starship release, I still need to use the port-forwarding script unfortunately.

Here is the yaml I use : 
```yaml
chains:
  - id: stargaze-1
    name: stargaze
    numValidators: 1
    ports:
      rest: 1313
      rpc: 26653
      grpc: 30658
      faucet: 8000
  - id: juno-1
    name: juno
    numValidators: 1
    ports:
      rest: 1317
      rpc: 26657
      grpc: 30657
      faucet: 8001

relayers:
  - name: osmo-juno
    type: hermes
    replicas: 1
    chains:
      - stargaze-1
      - juno-1

explorer:
  enabled: true
  ports:
    rest: 8080

registry:
  enabled: true
  ports:
    rest: 8081
```
