### ISSUE TITLE
consider combining starship.yaml and config.yaml into one

### ISSUE THREAD

**Issue by pyramation** [cosmology-tech/starship#466]

**Comment by Anmol1696** [comment]
Actually this makes the most sense. We can have:
```yaml
name: <helmName>
version: <helmVersion>

chains:
- ...
```

Here i would say we should rename everything so that we dont have `helm<xyz>` instead make it simpler and to the point. 

Non-required options could also include:
```yaml
name: <helmName>
version: <helmVersion>
repo: <helmRepo> # optional
chart: <helmChart> # optional

chains:
- ...
```
