### ISSUE TITLE
feature request: give wallets funds at startup

### ISSUE THREAD

**Issue by dakom** [cosmology-tech/starship#547]
oftentimes when developing you have a wallet that's hardcoded across different services (on-chain tests, bots, development tools, etc.)

it would be very helpful to simply tell Starship, in the config, to send funds to specific addresses on startup

without this feature, the only ways I'm aware of to accomplish the same thing are to manually patch the genesis, write external tooling to tap the faucet, or extract the genesis addresses and use those for product development - none of which are ideal.

I don't have a suggestion for if this would belong in its own field, faucet, etc... faucet may be the most organic, and simply have it "tap the faucet" for each address on startup, though this would disallow sending a specific amount afaict

**Comment by Anmol1696** [comment]
this is a really good suggestions. Let me figure out a way to add it to the config.

Does this look ok on the config:
```
chains:
  - id: osmosis-1
    name: osmosis
    numValidators: 2
    balances:
    - address: osmo14lzvt4gdwh2q4ymyjqma0p4j4aykpn929zx75y
      amount: 1000000000uosmo
    - address: osmo1clpqr4nrk4khgkxj78fcwwh6dl3uw4epasmvnj
      amount: 1000000000uosmo
  - id: cosmoshub-4
    name: cosmoshub
    numValidators: 2
    balances:
      - address: cosmos1c4k24jzduc365kywrsvf5ujz4ya6mwymy8vq4q
        amount: 1000000000uatom
      - address: cosmos196ax4vc0lwpxndu9dyhvca7jhxp70rmcfhxsrt
        amount: 1000000000uatom
```
