### ISSUE TITLE
bug: relayer does not start with Neutron

### ISSUE THREAD

**Issue by dakom** [cosmology-tech/starship#550]
with the following config, relayer just stays `Pending`. If I switch `Neutron` for `CosmosHub` then it does start fine:

```yaml
name: foo
 
chains:
  - id: neutron-1 
    name: neutron
    numValidators: 1
    faucet:
      enabled: false
    ports:
      rpc: 26657
      grpc: 9090

  - id: osmosis-1
    name: osmosis
    faucet:
      enabled: false
    numValidators: 1
    ports:
      rpc: 26658
      grpc: 9091

relayers:
  - name: neutron-osmosis 
    type: hermes
    replicas: 1
    chains:
      - neutron-1
      - osmosis-1
    ports:
      rest: 3001
      exposer: 3002
  
registry:
  enabled: true
  ports:
    rest: 8081
```

Some more logs, in case it helps:

```
$ kubectl get pods                                                                                                                                                                              
NAME                        READY   STATUS                  RESTARTS      AGE
hermes-neutron-osmosis-0    0/2     Init:CrashLoopBackOff   2 (23s ago)   113s
neutron-1-genesis-0         2/2     Running                 0             113s
osmosis-1-genesis-0         2/2     Running                 0             113s
registry-6fb4575c58-qr2s9   1/1     Running                 0             113s
```

```
$ kubectl logs hermes-neutron-osmosis-0                                                                                                                                                         
Defaulted container "relayer" out of: relayer, exposer, init-exposer (init), wait-for-chains (init), init-relayer (init)
Error from server (BadRequest): container "relayer" in pod "hermes-neutron-osmosis-0" is waiting to start: PodInitializing
```
