### ISSUE TITLE
bug: registry service not starting

### ISSUE THREAD

**Issue by fmorency** [cosmology-tech/starship#552]
The registry service fails to start with

```
Genesis validator does not seem to be ready for: manifest-ledger-beta. Waiting for it to start...
Checking: http://manifest-ledger-beta-genesis.default.svc.cluster.local:8081/node_id
```

Configuration is

```yaml
name: starship-manifestjs
version: v0.2.12

chains:
  - id: manifest-ledger-beta
    name: custom
    image: ghcr.io/liftedinit/manifest-ledger:v0.0.1-alpha.12
    home: /root/.manifest
    binary: manifestd
    prefix: manifest
    denom: umfx
    coins: 1000000000000000000umfx
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/liftedinit/manifest-ledger
    numValidators: 1
    ports:
      rest: 1317
      rpc: 26657
  - id: cosmos-2
    name: cosmoshub
    numValidators: 1
    ports:
      rest: 1313
      rpc: 26653

#relayers:
#  - name: manifest-cosmos
#    type: hermes
#    replicas: 1
#    chains:
#      - manifest-ledger-beta
#      - cosmos-2

registry:
  enabled: true
  ports:
    rest: 8081
```

```shell
# kubectl get pods
NAME                             READY   STATUS     RESTARTS   AGE
cosmos-2-genesis-0               3/3     Running    0          5m45s
manifest-ledger-beta-genesis-0   3/3     Running    0          5m45s
registry-f997744df-p524s         0/1     Init:0/1   0          5m45s
```

```shell
# helm list
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
starship-manifestjs     default         1               2024-09-05 09:47:04.036022695 -0400 EDT deployed        devnet-0.2.12   0.1.1 
```

Backend is `kind`.
