### ISSUE TITLE
feature: dockerfiles simplification: add a way to copy files or binaries

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship#597]
## Overview
We seem to have multiple docker images with very similaris dockerfiles as base with only difference in copying files from base images.

```Dockerfile
--- Dockerfile.eth-beacon
COPY --from=source /beacon-chain /usr/bin
--- Dockerfile.eth-prysmctl
COPY --from=source /prysmctl /usr/bin
--- Dockerfile.eth-validator
COPY --from=source /validator /usr/bin
---
```

## Options 1
We can either define a `copy` in `versions.yaml` which is a list.
```yaml
  - name: prysm/cmd/prysmctl
    base: gcr.io/prysmaticlabs/prysm/cmd/prysmctl
    file: Dockerfile.eth-prysmctl
    copy:
      - "/beacon-chain:/usr/bin"
    tags:
      - stable
      - v5.2.0
```

## Options 2
```yaml
  - name: prysm/cmd/prysmctl
    base: gcr.io/prysmaticlabs/prysm/cmd/prysmctl
    file: Dockerfile.eth-prysmctl
    copy:
      - src: "/beacon-chain"
        dst: "/usr/bin"
    tags:
      - stable
      - v5.2.0
```
