### ISSUE TITLE
improvements: Ability to patch genesis based on config input

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship#60]
## Overview

Currently the genesis.json for all the chains are created via a script in init-containers. There is a need to override certain genesis params based on user requirements or initialization of the cluster.

Example: Default fees for creation of pool in Osmosis is 1000 Osmo, set in genesis.json as 
```json
"app_state": {
...
    "gamm": {
      "pools": [],
      "next_pool_number": "1",
      "params": {
        "pool_creation_fee": [
          {
            "denom": "uosmo",
            "amount": "1000000000"
          }
        ]
      }
    },
...
```

## Proposal
We have a couple of solutions or approaches for this:
* Use `jq` to perform patchMerge, similar to how kustomize works in k8s yaml. The user interface via config file would look something like
```yaml
chains:
  - name: osmosis-1
    type: osmosis
    numValidators: 2
    overrides:
      genesis: |
        {
            "app_state": {
              "gamm": {
                "params": {
                  "pool_creation_fee": [
                    {
                      "denom": "uosmo",
                      "amount": "100000"
                    }
                  ]
                }
              }
            }
        }
```
or provide a json patch file as input
```
chains:
  - name: osmosis-1
    type: osmosis
    numValidators: 2
    overrides:
      genesis: custom-patchGenesis.json
```

* Provide users a way to provide a costom genesis script run `pre` or `post` after running the default scripts. We can also have the option to skip the default genesis creation script completely
```yaml
chains:
  - name: osmosis-1
    type: osmosis
    numValidators: 2
    overrides:
      genesis: 
        post: custom-genesis-script.sh
```
**Note:** custom scripts need to be based on the variabled provided by the original script
