### ISSUE TITLE
improvements: Add ability to specify multiple denoms in values.yaml

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship#72]
## Overview
Currently we are using `coins: 100000000000000uosmo,100000000000000uion` and `denom` in the default `values.yaml` file in `defaultChains`.

The side effect of this is, the registry service is currently only able to show a single denom in the assetlist.

## Proposal
Ability to specify multiple denoms as per the chain in the default values (based on the actual chain-registry)
```yaml
defaultChains:
  osmosis:
    image: anmol1696/osmosis:latest
    home: /root/.osmosisd
    binary: osmosisd
    prefix: osmo
    denom: uosmo
    denoms:
      - name: osmo
        # "<exp 0 denom>, <exp 6 denom>"
        units: "uosmo, osmo"
      - name: ion
        units: "uion, ion"
    coins: 100000000000000uosmo,100000000000000uion
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/osmosis-labs/osmosis
```
