### ISSUE TITLE
feature: Allow chain code to be built in place

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship#90]
## Overview
Currently we are building images when we specify the `upgrade:` key for a chain.

## Proposal
Allow in the config file to build the code from source in place.
```yaml
chains:
- name: core-1
  type: persistencecore
  numValidators: 2
  build:
    enabled: true
    source: <tag or commit>
```

Although we have some alternatives mentioned bellow, i think the featuer is important enough to be a standalone feature for Starship

### Custom Docker Image
We already support custom image for the chain (as long as the docker image has a bunch of prerequirsts).

One can clone the Dockerfile from `docker/chains/` [dir](https://github.com/cosmology-tech/starship/tree/main/docker/chains), push it to docker hub and mention that in the config"
```yaml
chains:
- name: core-1
  type: persistencecore
  image: <custom image>
  numValidators: 2
```

### Upgrade with only genesis
If one does not perform the chain upgrade via software upgrade proposal, then they can run the system with 
```yaml
- name: core-1
    type: persistencecore
    numValidators: 3
    upgrade:
      enabled: true
      type: build
      genesis: v7.0.0
```
This will build the tag from source and perpare the cosmovisor.
